### PR TITLE
skip failing tests

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Any updates on this?

**Comment by ltalirz** [comment]
@h-vetinari apologies for breaking the build & for the delay (business travel).

it should be fixed finally; just the osx arm64 build somehow seems stuck.
would it be safe to merge this PR nevertheless, what do you think?

**Comment by ltalirz** [comment]
Ah, it _did_ complete (after 4h). Merging

**Comment by h-vetinari** [comment]
Cool, thanks for fixing this! :)

**Pull request merged**
